### ISSUE TITLE
Chrome / Chromium support

### ISSUE THREAD

**Issue by avindra** [talwrii/curlfire#1]
It seems that Chrome / Chromium also stores cookies using sqlite3. An example gist which shows how to get the cookies from chrome:

https://gist.github.com/nicerobot/1443588

So we could theoretically make this script work with Chrome + Firefox

**Comment by talwrii** [comment]
Nice.

I think adding support for chrome would be a good addition to this tool and *curlfire's* repository is a good place for this feature to exist. Although, maybe it makes sense to set up a repository called *curlchrome* that merely links to *curlfire* to make finding this feature easy.

I'm definitely happy to accept pull requests for this feature and to maintain the code. I'm not sure how motivated I am to implement it however, since I don't use chrome and wouldn't use this feature.

Do you want to write a pull request for this? I'd be more than happy to give you any pointers you want in understanding the code.

**Comment by avindra** [comment]
Yeah I could take a stab at it some weekend. I wanted to just point it out for now, in case someone comes along and wants to try.

**Comment by talwrii** [comment]
>  I wanted to just point it out for now, in case someone comes along and wants to try.

A good plan. If we wait a little longer someone might come along and do the work for us :thinking: :smile:

**Comment by ChillerDragon** [comment]
Also there is https://github.com/jb55/curlc
